apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.6
    path: "/volume2/k8s-vol"